name: "build release tul"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: run magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build tul
        run: nix build -L .#release
